name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable corepack
        run: corepack enable
      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.store_path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Typecheck core packages
        run: |
          pnpm -r \
            --filter @startupquest/core \
            --filter @startupquest/ai \
            --filter @startupquest/analytics \
            typecheck
      - name: Generate Prisma client (api)
        run: pnpm --filter api run db:generate
      - name: Typecheck api
        run: pnpm --filter api run typecheck
      - name: Build api
        run: pnpm --filter api run build
